version: '3.3'
services:
  app:
    build: .
    image: "sphairas/server2:dev"
    deploy:
      resources:
        limits:
          # Set a hard limit (e.g., 4 CPU cores)
          cpus: '4.0'
          # Set a hard limit for memory (recommended)
          memory: 4096M 
        reservations:
          # Reserve a minimum number of CPU cores (e.g., 2 cores)
          cpus: '2.0'
          memory: 2048M
    ports:
      - "8080:8080"
      - "7781:7781"
      - "8181:8181"
      - "9009:9009"
      - "4848:4848"
    volumes:
      - "app-resources:/app-resources/"
      - "secrets:/run/secrets/"
    depends_on:
      - db
    environment:
      - "DB_HOST=db"
      - "DB_PORT=3306"
      - "DB_NAME=sphairas"
      - "DB_USER=sphairas"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "PAYARA_ARGS=--debug"
      - "TZ=Europe/Berlin"
#      - "JVM_ARGS=-Djavax.net.debug=all"
    env_file:
      - "docker.env"
    logging:
        driver: "json-file"
        options:
            max-size: "10m"
            max-file: "20"
  db:
    image: "mysql:5.7.30"
    ports:
      - "3306:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"
    environment:
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
      - "MYSQL_DATABASE=sphairas"
      - "MYSQL_USER=sphairas"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
volumes:
  app-resources:
  secrets:
  mysql-data:
